### ISSUE TITLE
Is this module compitable with ios 8 and greater?

### ISSUE THREAD

**Issue by mitulbhalia** [appcelerator-modules/ti.flurry#25]
Recently I tested this module with ios 8 and got following error.

[ERROR] :  Script Error Couldn't find module: ti.flurry for architecture: x86_64

**Comment by mitulbhalia** [comment]
any?

**Comment by mitulbhalia** [comment]
@ingo please reply to my query.

**Comment by cdrx** [comment]
Check the pending pull requests for this repo, there is a PR that adds 64bit support on iOS

**Comment by ingo** [comment]
@adesugbaa can you review the PR?

**Comment by ingo** [comment]
This has now been merged.

**Comment by mitulbhalia** [comment]
thank you guys. :)
