### ISSUE TITLE
No Support for 64-bit architecture?

### ISSUE THREAD

**Issue by kjschulz** [appcelerator-modules/ti.flurry#28]
I'm confused, the changelog says this ti.flurry 1.5 is compliant with Titanium 3.5 SDK and that it supports 64-bit architecture.  Every time I run my app with this module installed I get the following:
[ERROR] :  Script Error Couldn't find module: ti.flurry for architecture: x86_64

Please advise!

**Comment by ingo** [comment]
I see 1.6 as compatible: https://github.com/appcelerator-modules/ti.flurry/releases. Have you tried that version?

**Comment by kjschulz** [comment]
Thanks @ingo, I didn't realize that releases directory had a v1.6.  Think I'm good to go, much appreciated :)
