### ISSUE TITLE
UnsatisfiedLinkError on Android 6

### ISSUE THREAD

**Issue by shodanuk** [appcelerator-modules/ti.flurry#32]
My Android app that is using ti.flurry 1.3.0 is crashing on start up. No output is being sent to the Ti console but I can see an UnsatisfiedLinkError for lib/arm/libti.flurry.so in the Android Monitor logcat:

```
12-08 15:29:15.495: E/AndroidRuntime(7945): FATAL EXCEPTION: KrollRuntimeThread
12-08 15:29:15.495: E/AndroidRuntime(7945): Process: co.uk.**********.maapp, PID: 7945
12-08 15:29:15.495: E/AndroidRuntime(7945): java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/co.uk.**********.maapp-1/lib/arm/libti.flurry.so: has text relocations
12-08 15:29:15.495: E/AndroidRuntime(7945): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
12-08 15:29:15.495: E/AndroidRuntime(7945): 	at java.lang.System.loadLibrary(System.java:1076)
12-08 15:29:15.495: E/AndroidRuntime(7945): 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
12-08 15:29:15.495: E/AndroidRuntime(7945): 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
12-08 15:29:15.495: E/AndroidRuntime(7945): 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
12-08 15:29:15.495: E/AndroidRuntime(7945): 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
```

Disabling ti.flurry prevents the crash.

Please note: I can only recreate this crash on device (Nexus 5X), I can't repro it in Genymotion.

**Comment by jacobbudin** [comment]
I'm encountering the same issue (Nexus 5X, Android 6).

**Comment by ashcoding** [comment]
Thanks for bringing this up. Will look into this and get this resolved.

**Comment by ashcoding** [comment]
Created a ticket https://jira.appcelerator.org/browse/MOD-2181 for this issue.

**Comment by ashcoding** [comment]
@jacobbudin  @shodanuk 
Release 1.3.1 to address this issue is here https://github.com/appcelerator-modules/ti.flurry/releases/tag/android-1.3.1

I'll close this issue as this is now resolved.
